version: "2"

services:
  ihub-rest:
    build: .
    environment:
    - NODE_ENV
    - SERVER_PORT
    - PORT_DEBUG
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${PORT_DEBUG}:${PORT_DEBUG}"
    command: npm run docker_dev
    networks:
      - mf-nk
  # Mongo Database
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - /data/db
    ports:
      - 27017:27017
    networks:
      - mf-nk
networks:
  mf-nk:
    driver: bridge